insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Russia');
insert into Countries (Name) values ('Ukraine');
insert into Countries (Name) values ('Philippines');
insert into Countries (Name) values ('Peru');
insert into Countries (Name) values ('Saudi Arabia');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Sweden');
insert into Countries (Name) values ('Spain');
insert into Countries (Name) values ('Japan');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('Poland');
insert into Countries (Name) values ('Vietnam');
insert into Countries (Name) values ('Philippines');
insert into Authors (Name, Surname, CountryId) values ('Gale', 'Ahrens', 8);
insert into Authors (Name, Surname, CountryId) values ('Kort', 'Gianelli', 7);
insert into Authors (Name, Surname, CountryId) values ('Ola', 'Bagby', 6);
insert into Authors (Name, Surname, CountryId) values ('Antonia', 'Banks', 5);
insert into Authors (Name, Surname, CountryId) values ('Luis', 'Lutton', 5);
insert into Authors (Name, Surname, CountryId) values ('Pincas', 'Jertz', 4);
insert into Authors (Name, Surname, CountryId) values ('Mitchel', 'Bouchard', 1);
insert into Authors (Name, Surname, CountryId) values ('Christos', 'Stanners', 8);
insert into Authors (Name, Surname, CountryId) values ('Hermine', 'Dugdale', 10);
insert into Authors (Name, Surname, CountryId) values ('Charlotta', 'Blaise', 8);
insert into Authors (Name, Surname, CountryId) values ('Royall', 'Courtin', 12);
insert into Authors (Name, Surname, CountryId) values ('Ravi', 'Seaward', 11);
insert into Authors (Name, Surname, CountryId) values ('Seana', 'Hulance', 1);
insert into Authors (Name, Surname, CountryId) values ('Madelena', 'Moukes', 9);
insert into Authors (Name, Surname, CountryId) values ('Theodosia', 'Dumbare', 8);
insert into Authors (Name, Surname, CountryId) values ('Chrisy', 'Sumption', 10);
insert into Authors (Name, Surname, CountryId) values ('Annie', 'Tytler', 5);
insert into Authors (Name, Surname, CountryId) values ('Fallon', 'Casford', 6);
insert into Authors (Name, Surname, CountryId) values ('Susannah', 'Greaser', 12);
insert into Authors (Name, Surname, CountryId) values ('Billye', 'Bebbell', 7);
insert into Authors (Name, Surname, CountryId) values ('Dacey', 'Galea', 9);
insert into Authors (Name, Surname, CountryId) values ('Sayres', 'Rolfini', 14);
insert into Authors (Name, Surname, CountryId) values ('Bernelle', 'McGuggy', 2);
insert into Authors (Name, Surname, CountryId) values ('Sapphira', 'Faireclough', 15);
insert into Authors (Name, Surname, CountryId) values ('Christoper', 'Blaydes', 13);
insert into Authors (Name, Surname, CountryId) values ('Vivia', 'Leverage', 5);
insert into Authors (Name, Surname, CountryId) values ('Barbie', 'Sarl', 11);
insert into Authors (Name, Surname, CountryId) values ('Mandel', 'Tofful', 1);
insert into Authors (Name, Surname, CountryId) values ('Kermit', 'Toyne', 5);
insert into Authors (Name, Surname, CountryId) values ('Meta', 'Fannin', 10);
insert into Books (Name, Pages, AuthorId) values ('Battle in Heaven (Batalla en el cielo)', 321, 12);
insert into Books (Name, Pages, AuthorId) values ('Stander', 251, 1);
insert into Books (Name, Pages, AuthorId) values ('Dot and the Whale', 336, 15);
insert into Books (Name, Pages, AuthorId) values ('With Honors', 243, 11);
insert into Books (Name, Pages, AuthorId) values ('Dream Wife', 396, 1);
insert into Books (Name, Pages, AuthorId) values ('The Seventh Sin', 244, 28);
insert into Books (Name, Pages, AuthorId) values ('Four Feathers, The', 218, 28);
insert into Books (Name, Pages, AuthorId) values ('A Husband of Round Trip', 416, 6);
insert into Books (Name, Pages, AuthorId) values ('Cosmic Journey', 383, 6);
insert into Books (Name, Pages, AuthorId) values ('Don''t Worry, I''m Fine (Je vais bien, ne t''en fais pas)', 288, 2);
insert into Books (Name, Pages, AuthorId) values ('That Man from Rio', 304, 3);
insert into Books (Name, Pages, AuthorId) values ('Another Stakeout', 155, 18);
insert into Books (Name, Pages, AuthorId) values ('Crawlspace', 315, 30);
insert into Books (Name, Pages, AuthorId) values ('Holy Motors', 339, 18);
insert into Books (Name, Pages, AuthorId) values ('Robin Hood', 222, 29);
insert into Books (Name, Pages, AuthorId) values ('Johnny Was', 160, 30);
insert into Books (Name, Pages, AuthorId) values ('Monument Ave.', 290, 7);
insert into Books (Name, Pages, AuthorId) values ('Jeremy', 438, 30);
insert into Books (Name, Pages, AuthorId) values ('2046', 235, 16);
insert into Books (Name, Pages, AuthorId) values ('Wyrmwood', 216, 28);
insert into Books (Name, Pages, AuthorId) values ('When Will I Be Loved', 380, 15);
insert into Books (Name, Pages, AuthorId) values ('House of the Seven Gables, The', 429, 22);
insert into Books (Name, Pages, AuthorId) values ('Innerspace', 165, 17);
insert into Books (Name, Pages, AuthorId) values ('Road House', 261, 27);
insert into Books (Name, Pages, AuthorId) values ('Broadway Melody, The', 239, 7);
insert into Books (Name, Pages, AuthorId) values ('Lisztomania', 392, 19);
insert into Books (Name, Pages, AuthorId) values ('Soldier in the Rain', 234, 25);
insert into Books (Name, Pages, AuthorId) values ('Sorceress', 222, 19);
insert into Books (Name, Pages, AuthorId) values ('The Wonders', 188, 25);
insert into Books (Name, Pages, AuthorId) values ('49 Up', 230, 21);
insert into Books (Name, Pages, AuthorId) values ('December 7th', 332, 28);
insert into Books (Name, Pages, AuthorId) values ('Broken Circle Breakdown, The', 300, 19);
insert into Books (Name, Pages, AuthorId) values ('Pursuit of Happiness', 428, 25);
insert into Books (Name, Pages, AuthorId) values ('Katt Williams: The Pimp Chronicles Pt. 1', 409, 26);
insert into Books (Name, Pages, AuthorId) values ('Pumzi', 383, 1);
insert into Books (Name, Pages, AuthorId) values ('Whore', 403, 21);
insert into Books (Name, Pages, AuthorId) values ('SubUrbia', 380, 12);
insert into Books (Name, Pages, AuthorId) values ('20,000 Leagues Under the Sea', 437, 8);
insert into Books (Name, Pages, AuthorId) values ('Donnie Darko', 443, 16);
insert into Books (Name, Pages, AuthorId) values ('Corpse Bride', 299, 3);
insert into Books (Name, Pages, AuthorId) values ('Funny Girl', 372, 12);
insert into Books (Name, Pages, AuthorId) values ('Ballad of Jack and Rose, The', 291, 29);
insert into Books (Name, Pages, AuthorId) values ('White Palms (Fehér tenyér)', 320, 16);
insert into Books (Name, Pages, AuthorId) values ('Tomorrow Never Dies', 417, 16);
insert into Books (Name, Pages, AuthorId) values ('Cat-Women of the Moon (a.k.a. Rocket to the Moon)', 248, 23);
insert into Books (Name, Pages, AuthorId) values ('The Fat Albert Halloween Special', 366, 25);
insert into Books (Name, Pages, AuthorId) values ('Chappie', 220, 21);
insert into Books (Name, Pages, AuthorId) values ('Dr. Wai in the Scriptures with No Words (Mao xian wang)', 254, 9);
insert into Books (Name, Pages, AuthorId) values ('Tell No One (Ne le dis à personne)', 164, 29);
insert into Books (Name, Pages, AuthorId) values ('Hunting and Gathering (Ensemble, c''est tout)', 198, 29);